### ISSUE TITLE
estimate_tx_gas failing on xDai with AttributeError: 'str' object has no attribute 'keys'

### ISSUE THREAD

**Issue by adzialocha** [gnosis/gnosis-py#26]
**Describe the bug**

The estimation of gas fees for Safe transactions fails on xDai with the following exception: `AttributeError: 'str' object has no attribute 'keys'`. This error is also occurring in the relayer breaking all estimates.

**To Reproduce**

Use the following code to reproduce:

```python
from gnosis.eth import EthereumClient
from gnosis.safe import Safe

ethereum_client = EthereumClient('https://xdai.poanetwork.dev')
safe = Safe('0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC', ethereum_client)
result = safe.estimate_tx_gas('0x333d72F54CF17BA7A1971e7C7E9acB91C8B709d2', 0, '0xa2e62045', 0)
print(result)
```

Executing this code throws the following exception:

```
Traceback (most recent call last):
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 436, in estimate_tx_gas_with_safe
    result: HexBytes = self.w3.eth.call(tx, block_identifier=block_identifier)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/module.py", line 58, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/manager.py", line 158, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32015, 'message': 'VM execution error.', 'data': 'revert: \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00??'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    result = safe.estimate_tx_gas('0x333d72F54CF17BA7A1971e7C7E9acB91C8B709d2', 0, '0xa2e62045', 0)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 521, in estimate_tx_gas
    return self.estimate_tx_gas_by_trying(to, value, data, operation) + PROXY_GAS + OLD_CALL_GAS
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 490, in estimate_tx_gas_by_trying
    gas_estimated = self.estimate_tx_gas_with_safe(to, value, data, operation)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 456, in estimate_tx_gas_with_safe
    key = list(data_dict.keys())[0]
AttributeError: 'str' object has no attribute 'keys'
```

**Expected behavior**

The revert is happening as expected but seems to be not parseable in the `catch` phrase. I assume that the revert message looks slightly different on xDai than on mainnet?

**Some more observations**

* The code in `gnosis-py` checks for an capitalized *"Reverted ..."* data message, the xdai response is lowercase and *"revert: ..."*? https://github.com/gnosis/gnosis-py/blob/master/gnosis/safe/safe.py#L451
* The returned bytecode in `data` contains invalid values (here it is `??`).

**Comment by adzialocha** [comment]
When using `https://dark-frosty-field.xdai.quiknode.pro` as the RPC endpoint the error changes to `AttributeError: 'str' object has no attribute 'get'`, though I'm not sure if this is directly related or due to another problem of the quiknode:

```
Traceback (most recent call last):
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 436, in estimate_tx_gas_with_safe
    result: HexBytes = self.w3.eth.call(tx, block_identifier=block_identifier)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/module.py", line 58, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/manager.py", line 157, in request_blocking
    apply_error_formatters(error_formatters, response)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/manager.py", line 62, in apply_error_formatters
    formatted_response = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 518, in raise_solidity_error_on_revert
    raise ContractLogicError(f'execution reverted: {bytes.fromhex(reason).decode("utf8")}')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 30: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    result = safe.estimate_tx_gas('0x75bb5e5029A752faeF0716929b7384D0bC78DE88', 0, '0xa2e62045', 0)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 521, in estimate_tx_gas
    return self.estimate_tx_gas_by_trying(to, value, data, operation) + PROXY_GAS + OLD_CALL_GAS
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 490, in estimate_tx_gas_by_trying
    gas_estimated = self.estimate_tx_gas_with_safe(to, value, data, operation)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 448, in estimate_tx_gas_with_safe
    data_dict = error_dict.get('data')
AttributeError: 'str' object has no attribute 'get'
```

**Comment by Uxio0** [comment]
@adzialocha Would it be possible to have the exact parameters you are using to debug the issue?

**Comment by adzialocha** [comment]
> @adzialocha Would it be possible to have the exact parameters you are using to debug the issue?

The above mentioned python script is the one which should show the regarding error. I simply set up a python environment using the latest version of `gnosis-py` and `web3`. The safe address is my personal Circles safe `0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC`, the estimate with `0x333d72F54CF17BA7A1971e7C7E9acB91C8B709d2` points at my connected Circles Token Contract executing the `update` method `0xa2e62045`: https://github.com/CirclesUBI/circles-contracts/blob/master/contracts/Token.sol#L152

Let me know if you need anything else I can't think of right now! :+1:

**Comment by Uxio0** [comment]
@adzialocha I mean, what are the parameters you are giving to the estimate endpoint?

**Comment by adzialocha** [comment]
> @adzialocha I mean, what are the parameters you are giving to the estimate endpoint?

Currently all requests calling `POST` @ `https://relay.circles.garden/api/v2/safes/:safeAddress/transactions/estimate/` are failing with this error.

**Comment by Uxio0** [comment]
RPC is https://dark-frosty-field.xdai.quiknode.pro, right?

**Comment by MarekM25** [comment]
Hi @adzialocha @Uxio0

I'm from the Nethermind - eth client team. 

"The code in gnosis-py checks for an capitalized "Reverted ..." data message, the xdai response is lowercase and "revert: ..."? https://github.com/gnosis/gnosis-py/blob/master/gnosis/safe/safe.py#L451"

It could be a lack of standardization of Etherheum clients. Different clients could return different error messages. There is a lot of discussion in the ethereum community to standardize JSON RPC more. You can observe this project and propose your improvements here: https://github.com/ethereum-oasis/eth1.x-JSON-RPC-API-standard Our client returns an error message like: "revert" and I suppose that the parity client return "Reverted".

"The returned bytecode in data contains invalid values (here it is ??)."

That is interesting I checked with @adzialocha parameters that Nethermind returns a concrete number. I am not sure if it was our node or the parity node. However, if @Uxio0  you debug this issue and you will have a JSON RPC request I am eager to check it on our side too.

**Comment by adzialocha** [comment]
> RPC is https://dark-frosty-field.xdai.quiknode.pro, right?

On production we're using `https://rpc.xdaichain.com`

**Comment by adzialocha** [comment]
Thank you @MarekM25!

In the Circles Relayer (which is a fork of the Gnosis Relayer Service), we also experience this problem running against `https://rpc.xdaichain.com` since the 23rd of February, I'm not sure if its related to the above mentioned issue, but it occurs around gas estimation as well:

```
2021-02-24 18:00:29,464 [WARNING] [MainProcess] https://relay.circles.garden/api/v3/safes/predict/ - Exception: ValueError: {'code': -32603, 'message': 'Internal error', 'data': "Nethermind.State.InsufficientBalanceException: Exception of type 'Nethermind.State.InsufficientBalanceException' was thrown.\n   at Nethermind.State.StateProvider.SetNewBalance(Address address, UInt256& balanceChange, IReleaseSpec releaseSpec, Boolean isSubtracting) in /src/Nethermind/Nethermind.State/StateProvider.cs:line 211\n   at Nethermind.Evm.TransactionProcessor.Execute(Transaction transaction, BlockHeader block, ITxTracer txTracer, Boolean isCall) in /src/Nethermind/Nethermind.Evm/TransactionProcessor.cs:line 203\n   at Nethermind.Facade.BlockchainBridge.CallAndRestore(BlockHeader blockHeader, Int64 number, UInt256 timestamp, Transaction transaction, ITxTracer tracer) in /src/Nethermind/Nethermind.Facade/BlockchainBridge.cs:line 230\n   at Nethermind.Facade.BlockchainBridge.EstimateGas(BlockHeader header, Transaction tx, CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Facade/BlockchainBridge.cs:line 190\n   at Nethermind.JsonRpc.Modules.Eth.EthModule.EstimateGas(TransactionForRpc transactionCall, BlockHeader head) in /src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthModule.cs:line 422\n   at Nethermind.JsonRpc.Modules.Eth.EthModule.eth_estimateGas(TransactionForRpc transactionCall, BlockParameter blockParameter) in /src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthModule.cs:line 405"} - Data received {'salt_nonce': 229315587246305, 'owners': ['0xD1CD57B4A3ab304ce08c0506Fa44D08fB21e88E1'], 'threshold': 1}
```

The related code passage is here: https://github.com/CirclesUBI/safe-relay-service/blob/main/safe_relay_service/relay/services/safe_creation_service.py#L156

**Comment by Uxio0** [comment]
I'm trying:

`POST https://rpc.xdaichain.com/`

```json
{"jsonrpc":"2.0","method":"eth_call","params":[{"value": 0, "chainId": 100, "from": "0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC", "gasPrice": 0, "to": "0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC", "data": "0xc4ca3a9c000000000000000000000000333d72f54cf17ba7a1971e7c7e9acb91c8b709d20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004a2e6204500000000000000000000000000000000000000000000000000000000"}],"id":1}
```

Result:
```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32015,
        "message": "VM execution error.",
        "data":"revert: ??"
   }
  "id": 1
}
```

Version of the node `Geth/v1.8.15-omnibus-255989da/linux-amd64/go1.10.1`

Looks like this bug is related to Geth. I will push a fix to gnosis-py so it raises a controlled exception and another estimation method is used

**Comment by Uxio0** [comment]
@adzialocha I'm closing this as there's nothing I can do. This should be reported to the Geth team, but they might tell you you need to run an updated version of the node

**Comment by Uxio0** [comment]
I've tested it with `Geth/v1.9.25-stable-e7872729/linux-amd64/go1.15.6`, it's also failing

**Comment by Uxio0** [comment]
`OpenEthereum//v3.1.1-rc.1-stable/x86_64-linux-musl/rustc1.47.0` is doing the same:

```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32015,
        "message": "VM execution error.",
        "data": "Reverted 0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000002123"
    },
    "id": 1
}
```

Now it looks like there's a problem with the exceptions on web3.py, as they don't return `data` on the exception.

**Comment by Uxio0** [comment]
Ok, this is a `web.py` issue, not a node issue https://github.com/ethereum/web3.py/issues/1888

**Comment by MarekM25** [comment]
@adzialocha ,

The insufficient balance could be the correct response for estimte_gas sometimes. We will probably change how we return this error message (remove stack_trace and different message).


> I'm trying:
> 
> `POST https://rpc.xdaichain.com/`
> 
> ```json
> {"jsonrpc":"2.0","method":"eth_call","params":[{"value": 0, "chainId": 100, "from": "0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC", "gasPrice": 0, "to": "0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC", "data": "0xc4ca3a9c000000000000000000000000333d72f54cf17ba7a1971e7c7e9acb91c8b709d20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004a2e6204500000000000000000000000000000000000000000000000000000000"}],"id":1}
> ```
> 
> Result:
> 
> ```json
> {
>     "jsonrpc": "2.0",
>     "error": {
>         "code": -32015,
>         "message": "VM execution error.",
>         "data":"revert: ??"
>    },
>   "id": 1
> }
> ```
> 
> Version of the node `Geth/v1.8.15-omnibus-255989da/linux-amd64/go1.10.1`
> 
> Looks like this bug is related to Geth. I will push a fix to gnosis-py so it raises a controlled exception

It seems like a response from our Nethermind nodes. I will investigate it further. @Uxio0 could you tell me how did you check the version of the node?

**Comment by Uxio0** [comment]
> It seems like a response from our Nethermind nodes. I will investigate it further. @Uxio0 could you tell me how did you check the version of the node?

```json
{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}
```

**Comment by MarekM25** [comment]
@Uxio0 thx for your response. Yes, I think we have something wrong there. I will analyze it :)

**Comment by habdelra** [comment]
@MarekM25 now that POA is moving to using nethermind for its recommended ethereum node, it is really difficult to use gnosis safes in POA or Sokol, since the gnosis relay server may run into this error. Is there a timeframe for when a fix will be available for this?
